---
- name: Config | Configuring DRBD
  ansible.builtin.template:
    src: etc/drbd.d/global_common.conf.j2
    dest: /etc/drbd.d/global_common.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Config | Loading DRBD Kernel Module
  community.general.modprobe:
    name: drbd
    state: present
  become: true

- name: Config | Ensuring drbd Service Is NOT Enabled On Boot
  ansible.builtin.service:
    name: drbd
    enabled: false
  become: true
