---
# tasks file for ansible-drbd

# - name: Debian
#   ansible.builtin.include_tasks: debian.yml
#   tags:
#     - drbd
#     - drbd-install
#   when: ansible_os_family == "Debian"

- name: Red Hat
  ansible.builtin.include_tasks: redhat.yml
  tags:
    - drbd
    - drbd-install
  when: ansible_os_family == "RedHat"

- name: Config
  ansible.builtin.include_tasks: config.yml
  tags:
    - drbd
    - drbd-config

- name: Disk Setup
  ansible.builtin.include_tasks: disks.yml
  tags:
    - drbd
    - drbd-disks
