---
- name: Import the ELRepo gpg key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - 'https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'
    - 'https://www.elrepo.org/RPM-GPG-KEY-v2-elrepo.org'

- name: Install the ELRepo repository
  ansible.builtin.dnf:
    name: 'https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm'
    state: present

- name: Install DRBD
  ansible.builtin.dnf:
    name: "{{ drbd_rpm_packages }}"
    state: present
